# Generated by Django 3.0.6 on 2021-01-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=100)),
                ('sub', models.CharField(max_length=55)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
